language: java
jdk: openjdk11
before_install:
  - sudo apt-get -y install python3 python3-venv
addons:
  apt:
    update: true
script:
  - ./build.sh
cache:
  - $HOME/.m2
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: travis
